### ISSUE TITLE
DEX: 23 passing 11 failing

### ISSUE THREAD

**Issue by gluneau** [AcalaNetwork/truffle-tutorials#24]
Tutorial needs revisions to account for EVM RPC changes

![image](https://user-images.githubusercontent.com/2903505/173152067-be5f7c4b-c331-4321-8049-d612c2bfae2d.png)

**Comment by gluneau** [comment]
Still a few errors, including `RPC-CORE: submitExtrinsic(extrinsic: Extrinsic): Hash:: 1010: Invalid Transaction: Transaction is outdated`

![image](https://user-images.githubusercontent.com/2903505/173359344-b8dca1b9-7c6c-425f-865a-3740f3c43d79.png)

**Comment by zjb0807** [comment]
<img width="930" alt="image" src="https://user-images.githubusercontent.com/16496415/173366135-44ca0c1a-26ba-490a-86da-655add81745a.png">
The ACA/DOT trading pair was enabled on the mandala, so the test cases are broken.

**Comment by gluneau** [comment]
@ThunderDeliverer, can you pick another nonexistant pair?
